<?php

namespace ContainerHGHkDcx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GNEJ4sCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GNEJ4sC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GNEJ4sC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cache' => ['services', 'cache.app', 'getCache_AppService', false],
            'markdownParser' => ['services', 'markdown.parser', 'getMarkdown_ParserService', false],
        ], [
            'cache' => '?',
            'markdownParser' => '?',
        ]);
    }
}
