<?php

namespace ContainerDX4Hoyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WzgG3XlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WzgG3Xl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WzgG3Xl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommentController::commentVote' => ['privates', '.service_locator.OC2AG.K', 'get_ServiceLocator_OC2AG_KService', true],
            'App\\Controller\\QuestionController::show' => ['privates', '.service_locator.GNEJ4sC', 'get_ServiceLocator_GNEJ4sCService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\CommentController:commentVote' => ['privates', '.service_locator.OC2AG.K', 'get_ServiceLocator_OC2AG_KService', true],
            'App\\Controller\\QuestionController:show' => ['privates', '.service_locator.GNEJ4sC', 'get_ServiceLocator_GNEJ4sCService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\CommentController::commentVote' => '?',
            'App\\Controller\\QuestionController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommentController:commentVote' => '?',
            'App\\Controller\\QuestionController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
