<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDX4Hoyx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDX4Hoyx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDX4Hoyx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDX4Hoyx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDX4Hoyx\App_KernelDevDebugContainer([
    'container.build_hash' => 'DX4Hoyx',
    'container.build_id' => 'bf9a3f86',
    'container.build_time' => 1700681501,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDX4Hoyx');
